### ISSUE TITLE
spell selection feature nonfunctional and breaks UI

### ISSUE THREAD

**Issue by wtfBbqException** [jennyem/pathfinder-mods#37]
Whenever a feature from EA requires you to select a spell, it breaks the UI.

EA release: Apr 4
PF:K version: EE, v. 2.0.3 and 2.0.4

Examples where I have run into this issue:
- spell specialisation feat
- spell replacement feature for sorcs

Observable result: Fly-out list stays empty, in the case of spell replacement you'll get stuck. Aborting the level-up process is possible, but irrevocably breaks any level-up UI: the entire 'book' is empty then, even for characters that have no spellcasting. Reloading fixes the UI, but the feature remains nonfunctional. The log from ModManager says nothing.

**Comment by PortlyAssassin** [comment]
This also occurs on traits where a spell is selected, such as Metamagic Master and Signature Spell.

**Comment by Ravendarke8** [comment]
Any feat that has drop menu for specific selection will cause that. There is some interaction going on, because for few levels this worked, from specific level on it will just make any feat with drop menu impossible to select. It will furthermore break whole gui (upon closing and reopening character level up screen whole screen will be black and you will get stuck here). This is critical issue.

**Comment by wtfBbqException** [comment]
Hm. I was just notified via comment on nexusmods that the release 0.6.9.2 supposedly fixes this issue. I thought I had tested that version, but decided to try again with a fresh download. On a new character, I could successfully pick a spell for the spell specialisation feat. I haven't had the time yet to test it out completely, esp. with a character lvl > 1, but I'm cautiously hopeful!

**Comment by wtfBbqException** [comment]
Can confirm that the latest release fixes this issue.

Thank you :)

**Comment by PortlyAssassin** [comment]
I still see this issue, even with a new download of this mod. Could you give some more info of what else you did to resolve this problem?
Did/do you have any other mods also installed?

**Comment by wtfBbqException** [comment]
That is weird. Given my previous experiences I'm getting the creeping suspicion that it's got to do with the Mod Manager and the versioning, which seems out-of-order (i.e., the newer release has a lower version number than the one it replaces). Have you deleted the EA folder in the Mod Manager folder entirely before reinstalling? That might have fixed it for me.

**Comment by PortlyAssassin** [comment]
No Joy, deleting the EA folder doesn't seem to make any difference. Wierd bug, guess I will wait until a new version is released. Thanks for your help.

**Comment by Cortillaen** [comment]
I initially installed the Nexus version of EA (MM registered it as 0.9.5), then came here and got the latest update (0.9.6.2).  MM accepted that zip and updated the mod, but reports the version as 0.9.6 both in the MM app and in the in-game UI.  When I deleted the EA folder and installed straight from the 0.9.6.2 zip, MM reports the version as 0.9.5.

In all cases, Magical Lineage (and I suspect other things requiring you to select a spell) cause the UI to become mostly unresponsive after selecting a spell level during character creation.  I can change pages but cannot change anything on the character.  The only fix is completely restarting the game.

**Comment by Cortillaen** [comment]
Could this be the issue?  I checked out the Info.json in your zip, and this is the content:
```json
{
  "Id": "EldritchArcana",
  "DisplayName": "Eldritch Arcana",
  "Author": "Elmindra",
  "Version": "0.9.5",
  "ManagerVersion": "0.12.2",
  "EntryMethod": "EldritchArcana.Main.Load",
  "HomePage": "https://github.com/jennyem/pathfinder-mods",
  "Repository": "https://raw.githubusercontent.com/jennyem/pathfinder-mods/master/EldritchArcana/Repository.json"
}
```

**Comment by Fawstus** [comment]
Hello there! Similar issue, I guess, but I am yet to find a way to fix spell selection within Traits. Is there a way to fix it? Thanks :)

**Comment by wtfBbqException** [comment]
Just to be sure we're not missing something... the way it worked for me was as follows (assuming standard installation options):
1. Go to "%modmanager-folder%\pathfinder kingmaker"
2. Delete the "Eldritch Arcana" subfolder
3. Run Modmanager and confirm that EA is not listed in the available mods
4. Drag and drop the zip you downloaded from the /release page here on github onto the appropriate field in ModManager
5. Cross your fingers, fire up the game
