### ISSUE TITLE
Spell Perfection - Spell selection window is blank

### ISSUE THREAD

**Issue by Pandastan** [jennyem/pathfinder-mods#41]
Just tried out your awesome mod, but got a bug straight away:

Wizard leveled up to lvl 15, wanted to learn "Spell perfection", but as soon as you klick on the feat it  kind of gets stuck. The Window for choosing the spell is not opening. If you go back to "Skills" and than again to "Abilities" you see the empty Spell-Selection window. From this on you are unable to progress in the levelup.

Game Version: 2.0.5c
UMM: 0.20.0.0
Active Mods: only EldritchArcana

Steps to reproduce:

1. Go to "Abilities" in the level up process
2. Select "Spell perfection"
-> Now you are Stuck.

3. Press "Back" to go back to "Skills"
4. Go back to "Abilities"
Now you should see this:
![image](https://user-images.githubusercontent.com/28513992/61241295-8a830300-a743-11e9-8dba-91dee9f44389.png)

If you exit the level-up process and reenter it, you are stuck with this screen:
![image](https://user-images.githubusercontent.com/28513992/61241384-b0100c80-a743-11e9-9d0f-dc017efa0b1f.png)

Also the "Total"-screen seems to bug after this:
![image](https://user-images.githubusercontent.com/28513992/61242061-16e1f580-a745-11e9-9181-18f25f12fe2a.png)

Reload resets everything back to normal.

This is the Output-Log for the exact moment i select the feat:
[output_log.txt](https://github.com/jennyem/pathfinder-mods/files/3393777/output_log.txt)

Full log:
[output_log.txt](https://github.com/jennyem/pathfinder-mods/files/3393797/output_log.txt)

**Comment by wtfBbqException** [comment]
Are you sure you are using the latest version? You didn't specify which EA version you are using. 0.9.6.2 fixed this kind of selection/UI breakage for me.

**Comment by Pandastan** [comment]
I just checked, it says 0.9.6. Its the latest version from the nexus, which was uploaded on 4. april. Seems like the last time this repo was updated was also the 4. April. So i assume it should be 0.9.6.2, but neither the version file nor the UMM tells me something besides "0.9.6"

**Comment by wtfBbqException** [comment]
0.9.6 means you're using an old version. The nexus version is OLDER than the one released here despite showing a higher version number in the MM (as you say yourself, the nexus release is from April -- the current release here on github is from June).

If you download and install the latest version (0.9.6.2) from here, MM will show it as '0.9.5' and ask you to update from nexus. It's misleading and simply due to version numbers being out-of-whack.

**Comment by Pandastan** [comment]
Hmm ok, but as im not very familiar with modding Pathfinder:
The latest release here on github(as found on the release site) is 0.9.6 from the 4. April. Where can i find the 0.9.6.2?

**Comment by wtfBbqException** [comment]
I don't know where you're looking. This is the page you need:

https://github.com/Redjordan/pathfinder-mods/releases

0.9.6.2 right at the top, June 11.

**Comment by Pandastan** [comment]
Ah thank you. Didn't know i had to look at Redjordans fork of this repo.
Yes, 0.9.6.2 fixed the problem. Thank you very much.
