### ISSUE TITLE
Error with 1.2.2 patch - Some Assets failed to load error 

### ISSUE THREAD

**Issue by astewart42** [jennyem/pathfinder-mods#7]
Error with version 1.2.2 , Some assets failed to load. 
String error when trying to load saves which used Eldritch Arcana mod. 
Haven't been able to fix it myself

amazing mod btw!

**Comment by ALFAIthildur** [comment]
Game is now at patch 1.2.3 
Savegames that have assets altered by Eldritch Arcana cannot be loaded.

**Comment by elmindra** [comment]
Thanks for letting me know! I'm about to release a fix.

**Comment by elmindra** [comment]
should be fixed in 0.9.4
